### ISSUE TITLE
AWS ERROR: InvalidImageFormatException

### ISSUE THREAD

**Issue by samsamimi** [khawerrind/go-aws-face-rekognition#1]
GIN-debug] POST   /v1/findFaces             --> github.com/khawerrind/go-aws-face-rekognition/controllers.(*MainController).FindFaces-fm (3 handlers)
[GIN-debug] Environment variable PORT is undefined. Using port :8080 by default
[GIN-debug] Listening and serving HTTP on :8080
AWS ERROR: InvalidImageFormatException: Face Compare Target Image Invalid encoding
	status code: 400, request id: 596156c9-912c-11e8-b2d7-83bb642d1148
AWS ERROR: InvalidImageFormatException: Face Compare Target Image Invalid encoding
	status code: 400, request id: 594bac23-912c-11e8-b181-d5c546fe82b0
AWS ERROR: InvalidImageFormatException: Face Compare Target Image Invalid encoding
	status code: 400, request id: 59783a97-912c-11e8-ac52-93e09856c63d
AWS ERROR: InvalidImageFormatException: Face Compare Target Image Invalid encoding
	status code: 400, request id: 596267d5-912c-11e8-84bd-8f9bc2868dc2

It always returns an empty array because processing of the file fails.  I have uploaded the same .png and .jpg files to S3 buckets so it is suppose to work. please advice

**Comment by filinvadim** [comment]
Is this project abandoned? I'm getting same error.

**Comment by khawerrind** [comment]
Sorry for the late reply. Which go version are you using. I have tested it with `go1.11.5` and it does not seems to have problems. Can you show me your postman request?

**Comment by khawerrind** [comment]
This issue was happening because AWS `ListObjects` was returning parent folder as object as well. Now added the check for checking if the file is an image i.e `.jpg`, `.jpeg` & `.png` only then AWS service will be called to compare both images.
